package model.AMs;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 28 23:26:56 AST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Countries1_1.
     * @return Countries1_1
     */
    public ViewObjectImpl getCountries1_1() {
        return (ViewObjectImpl) findViewObject("Countries1_1");
    }

    /**
     * Container's getter for Departments1.
     * @return Departments1
     */
    public ViewObjectImpl getDepartments1() {
        return (ViewObjectImpl) findViewObject("Departments1");
    }

    /**
     * Container's getter for EmpDetailsView1.
     * @return EmpDetailsView1
     */
    public ViewObjectImpl getEmpDetailsView1() {
        return (ViewObjectImpl) findViewObject("EmpDetailsView1");
    }

    /**
     * Container's getter for EmployeeTasks1.
     * @return EmployeeTasks1
     */
    public ViewObjectImpl getEmployeeTasks1() {
        return (ViewObjectImpl) findViewObject("EmployeeTasks1");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public ViewObjectImpl getEmployees1() {
        return (ViewObjectImpl) findViewObject("Employees1");
    }

    /**
     * Container's getter for JobHistory1.
     * @return JobHistory1
     */
    public ViewObjectImpl getJobHistory1() {
        return (ViewObjectImpl) findViewObject("JobHistory1");
    }

    /**
     * Container's getter for Jobs1.
     * @return Jobs1
     */
    public ViewObjectImpl getJobs1() {
        return (ViewObjectImpl) findViewObject("Jobs1");
    }

    /**
     * Container's getter for Locations1.
     * @return Locations1
     */
    public ViewObjectImpl getLocations1() {
        return (ViewObjectImpl) findViewObject("Locations1");
    }

    /**
     * Container's getter for Regions1.
     * @return Regions1
     */
    public ViewObjectImpl getRegions1() {
        return (ViewObjectImpl) findViewObject("Regions1");
    }

    /**
     * Container's getter for ViolationRecord1.
     * @return ViolationRecord1
     */
    public ViewObjectImpl getViolationRecord1() {
        return (ViewObjectImpl) findViewObject("ViolationRecord1");
    }

    /**
     * Container's getter for Departments2.
     * @return Departments2
     */
    public ViewObjectImpl getDepartments2() {
        return (ViewObjectImpl) findViewObject("Departments2");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public ViewObjectImpl getEmployees2() {
        return (ViewObjectImpl) findViewObject("Employees2");
    }

    /**
     * Container's getter for Employees3.
     * @return Employees3
     */
    public ViewObjectImpl getEmployees3() {
        return (ViewObjectImpl) findViewObject("Employees3");
    }

    /**
     * Container's getter for Employees4.
     * @return Employees4
     */
    public ViewObjectImpl getEmployees4() {
        return (ViewObjectImpl) findViewObject("Employees4");
    }

    /**
     * Container's getter for JobHistory2.
     * @return JobHistory2
     */
    public ViewObjectImpl getJobHistory2() {
        return (ViewObjectImpl) findViewObject("JobHistory2");
    }

    /**
     * Container's getter for JobHistory3.
     * @return JobHistory3
     */
    public ViewObjectImpl getJobHistory3() {
        return (ViewObjectImpl) findViewObject("JobHistory3");
    }

    /**
     * Container's getter for JobHistory4.
     * @return JobHistory4
     */
    public ViewObjectImpl getJobHistory4() {
        return (ViewObjectImpl) findViewObject("JobHistory4");
    }

    /**
     * Container's getter for Departments3.
     * @return Departments3
     */
    public ViewObjectImpl getDepartments3() {
        return (ViewObjectImpl) findViewObject("Departments3");
    }

    /**
     * Container's getter for Locations2.
     * @return Locations2
     */
    public ViewObjectImpl getLocations2() {
        return (ViewObjectImpl) findViewObject("Locations2");
    }

    /**
     * Container's getter for Countries1_2.
     * @return Countries1_2
     */
    public ViewObjectImpl getCountries1_2() {
        return (ViewObjectImpl) findViewObject("Countries1_2");
    }

    /**
     * Container's getter for DeptMgrFkVL1.
     * @return DeptMgrFkVL1
     */
    public ViewLinkImpl getDeptMgrFkVL1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkVL1");
    }

    /**
     * Container's getter for EmpManagerFkVL1.
     * @return EmpManagerFkVL1
     */
    public ViewLinkImpl getEmpManagerFkVL1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkVL1");
    }

    /**
     * Container's getter for EmpDeptFkVL1.
     * @return EmpDeptFkVL1
     */
    public ViewLinkImpl getEmpDeptFkVL1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkVL1");
    }

    /**
     * Container's getter for EmpJobFkVL1.
     * @return EmpJobFkVL1
     */
    public ViewLinkImpl getEmpJobFkVL1() {
        return (ViewLinkImpl) findViewLink("EmpJobFkVL1");
    }

    /**
     * Container's getter for JhistDeptFkVL1.
     * @return JhistDeptFkVL1
     */
    public ViewLinkImpl getJhistDeptFkVL1() {
        return (ViewLinkImpl) findViewLink("JhistDeptFkVL1");
    }

    /**
     * Container's getter for JhistEmpFkVL1.
     * @return JhistEmpFkVL1
     */
    public ViewLinkImpl getJhistEmpFkVL1() {
        return (ViewLinkImpl) findViewLink("JhistEmpFkVL1");
    }

    /**
     * Container's getter for JhistJobFkVL1.
     * @return JhistJobFkVL1
     */
    public ViewLinkImpl getJhistJobFkVL1() {
        return (ViewLinkImpl) findViewLink("JhistJobFkVL1");
    }

    /**
     * Container's getter for DeptLocFkVL1.
     * @return DeptLocFkVL1
     */
    public ViewLinkImpl getDeptLocFkVL1() {
        return (ViewLinkImpl) findViewLink("DeptLocFkVL1");
    }

    /**
     * Container's getter for LocCIdFkVL1.
     * @return LocCIdFkVL1
     */
    public ViewLinkImpl getLocCIdFkVL1() {
        return (ViewLinkImpl) findViewLink("LocCIdFkVL1");
    }

    /**
     * Container's getter for CountrRegFkVL1.
     * @return CountrRegFkVL1
     */
    public ViewLinkImpl getCountrRegFkVL1() {
        return (ViewLinkImpl) findViewLink("CountrRegFkVL1");
    }
}

